### ISSUE TITLE
Unable to close the emoji picker after clicking outside it

### ISSUE THREAD

**Issue by eakenbor** [jm-david/emoji-mart-vue#63]
I have tried using custom vue directives to close the modal upon clicking outside it but does not work as the event is triggered prematurely irrespective of the root element it is placed. Is there any inbuilt custom event for this? Or anyway around it?

**Comment by OneMoreRound82** [comment]
It would be good if there was a simple 'x' on the pop up to close the modal.  Can this be easily done?

**Comment by merfed** [comment]
This can easily be done with placing a div that gets displayed when you toggle the picker.

```vue
<div 
    class="modal-container"
    v-show="showEmojiPicker"
    @click="toggleEmojiPicker"></div>
```

```css
.modal-container {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1010;
}
```

And then adjust the z-index of the emoji-mart container. Which I think by default is 1 or 2.

```css
.emoji-mart {
    z-index: 1020;
}
```
